nacos:
  port: 8848
  host: localhost
servers:
  user:
    port: 8080
    host: localhost
  gateway:
    port: 8081
    host: localhost
  auth:
    port: 8082
    host: localhost
db:
  redis:
    port: 6379
    host: localhost
  mysql:
    port: 3306
    host: localhost
    username: root
    password: root
    database: uno
